#!/usr/bin/env ruby
site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'docker'
cookbook 'homesick'
cookbook 'platform_packages'
cookbook 'python'
cookbook 'vagrant'

cookbook 'modules',
  :git => 'https://github.com/patcon/modules-cookbook.git',
  :ref => 'fix-open-hash'

cookbook 'dropbox',
  :github => 'peplin/dropbox-cookbook'

cookbook 'janus',
  # Pending PR: https://github.com/pwelch/chef-janus/pull/3
  :github => 'patcon/chef-janus',
  :ref => 'ensure-rake-present'

cookbook 'patcon',
  :path => 'site-cookbooks/patcon'

# Sprout

cookbook 'meta',
  :path => 'site-cookbooks/meta'

cookbook 'sprout-osx-rbenv',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-osx-rbenv'

cookbook 'sprout-osx-git',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-osx-git'

cookbook 'sprout-osx-base',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-osx-base'

cookbook 'pivotal_workstation',
  :github => 'pivotal-sprout/sprout',
  :path => 'pivotal_workstation'

cookbook 'sprout-osx-apps',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-osx-apps'

cookbook 'sprout-osx-settings',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-osx-settings'

cookbook 'sprout-pivotal',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-pivotal'

cookbook 'osx',
  :github => 'pivotal-sprout/sprout',
  :path => 'osx'

cookbook 'sprout-osx-rubymine',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-osx-rubymine'

cookbook 'sprout-homebrew',
  :github => 'pivotal-sprout/sprout-homebrew'
